version: '3.8'
services:
  backend:
    build:
      context: ./back-end
    container_name: backend
    restart: always
    environment:
      DB_URL: 
      DB_URL_LOCAL: mongodb://127.0.0.1:27017/employee_db
      PORT: 9123
      JWT_SECRET: 
      JWT_EXPIRES_IN:
      JWT_COOKIE_EXPIRES_IN:
      EMAIL_USERNAME: 
      EMAIL_PASSWORD: 
      EMAIL_HOST:
      EMAIL_PORT:
      EMAIL_FROM:
      MINIO_ENDPOINT: 
      MINIO_USERNAME: 
      MINIO_PASSWORD: 
      NODE_ENV: 
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "9123:9123"
    networks:
      - ems-net

  frontend:
    build:
      context: ./front-end
    container_name: frontend
    restart: always
    environment:
      PORT: 3123
      GENERATE_SOURCEMAP: false
      REACT_APP_PUBLIC_IP_API: https://api.ipify.org?format=json
    depends_on:
      - backend
    ports:
      - "3123:3123"
    networks:
      - ems-net

networks:
  ems-net:
    driver: bridge