export enum STATUS {
    ACTIVE = 'active',
    INACTIVE = 'inactive',
    PENDING = 'Pending',
    SUSPENDED = 'suspended',
    DELETED = 'deleted',
    ARCHIVED = 'archived',
    COMPLETED = 'completed',
    FAILED = 'failed',
    APPROVED = 'Approved',
    REJECTED = 'Rejected',
    CANCELLED = 'Cancelled',
    ACCOUNT_CREATE_REQUEST = 'ACCOUNT_CREATE_REQUEST',
    LEAVE_REQUEST = 'LEAVE_REQUEST',
    SALARY_APPROVED = 'SALARY_APPROVED',
    SALARY_INCREASE = 'SALARY_INCREASE',
    DEPARTMENT_TRANSFER = 'DEPARTMENT_TRANSFER',
    TRAINING_PROPOSAL = 'TRAINING_PROPOSAL',
    PROFILE_UPDATE = 'PROFILE_UPDATE',
    PRESENT = 'present',
    LEAVE = 'leave',
    NGHI_THAI_SAN = 'leave_maternity',
    NGHI_KHONG_LUONG = 'leave_unpaid',
    NGHI_VO_SINH = 'leave_paternity',
    NGHI_CUOI = 'leave_marriage',
    NGHI_TANG = 'leave_funeral',
    NGHI_LAM_TU_XA = 'leave_remote_work',
    LATE = 'late',
    NGHI_OM = 'leave_sick',
    VE_SOM = 'leave_early',
    OVERTIME = 'overtime',
    OVERTIME_REQUEST = 'OVERTIME_REQUEST',
    TARGET_REQUEST = 'TARGET_REQUEST',
    WORKING_TIME_SETTINGS = 'WORKING_TIME_SETTINGS',
    SALARY_SETTINGS = 'SALARY_SETTINGS',
    ANNUAL_LEAVE = 'ANNUAL_LEAVE',             // Nghỉ phép năm
    SICK_LEAVE = 'SICK_LEAVE',                 // Nghỉ ốm
    UNPAID_LEAVE = 'UNPAID_LEAVE',             // Nghỉ không lương
    MATERNITY_LEAVE = 'MATERNITY_LEAVE',       // Nghỉ thai sản
    PATERNITY_LEAVE = 'PATERNITY_LEAVE',       // Nghỉ vợ sinh con
    MARRIAGE_LEAVE = 'MARRIAGE_LEAVE',         // Nghỉ cưới
    FUNERAL_LEAVE = 'FUNERAL_LEAVE',           // Nghỉ tang
    COMPENSATORY_LEAVE = 'COMPENSATORY_LEAVE', // Nghỉ bù
    REMOTE_WORK = 'REMOTE_WORK',               // Làm việc từ xa
    OTHER = 'OTHER',                            // Nghỉ lý do khác
    DU_THAO = '00',
    DA_DUYET = '01'
  }
